import cv2
import os
import sys


def extract_frames_with_timestamps(video_path, output_folder):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

'''
TODO: 
- Add the extraction code from threshold_tester.py
- Add as arguments to cli for similarity_threshold and frame_skipping / desired fps
- Default settings as sim_thresh = 0.95 and fps = 1.0
- Add function to calculate fps from video time / # frames -> cast to an int for a rate for frame_skipping
- Implement a loader for the autogenerated.vtt file
- Use timestamp to extract the associated .vtt caption
- Use image2text to get a description of the image and extract text from the image
- Bundle caption, image, image description, and text from the image -> dataset
- Make API calls to a multimodal LLM to correct .vtt caption (Google Gemini)
- Test a local multimodal LLM to see its performance compared to the multimodal one
'''

    # Load the video
    video = cv2.VideoCapture(video_path)

    # Get the frame rate of the video
    fps = video.get(cv2.CAP_PROP_FPS)

    frame_count = 0
    timestamps = {}  # Dictionary to store frame timestamps

    while True:
        success, frame = video.read()
        if not success:
            break

        # Calculate the timestamp of the current frame
        timestamp = frame_count / fps
        formatted_timestamp = f"{timestamp:.3f}"  # Format to 3 decimal places

        # Save the frame as a JPEG file
        filename = f"frame_{frame_count:04d}_{formatted_timestamp}s.jpg"
        output_path = os.path.join(output_folder, filename)
        cv2.imwrite(output_path, frame)

        # Store the timestamp in the dictionary
        timestamps[filename] = formatted_timestamp

        frame_count += 1

    video.release()

    # Optionally, save the timestamps to a file
    with open(os.path.join(output_folder, 'timestamps.txt'), 'w') as f:
        for filename, timestamp in timestamps.items():
            f.write(f"{filename}: {timestamp}s\n")

### Parse arguments ###
if len(sys.argv) < 2:
	print("Incorrect usage.")
	print("python autocaption.py video.mp4")
	sys.exit(0)


# Usage
video_path = sys.argv[1]  
output_folder = 'extracted_frames'  # Folder to save the extracted images

extract_frames_with_timestamps(video_path, output_folder)

